"""Reusable UI components for the demistifAI experience."""

from . import terminal
from .data import (
    _highlight_spans_html,
    data_review_styles,
    dataset_balance_bar_html,
    dataset_snapshot_active_badge,
    dataset_snapshot_card_html,
    dataset_snapshot_styles,
    edge_case_pairs_html,
    pii_chip_row_html,
    render_pii_cleanup_banner,
    render_pii_indicators,
    stratified_sample_cards_html,
)
from .evaluate import (
    render_guardrail_audit,
    render_guardrail_panel,
    render_threshold_controls,
)
from .intro import (
    intro_hero_scoped_css,
    intro_lifecycle_columns,
    render_intro_hero,
)
from .overview import (
    ArchitectureCard,
    demai_architecture_markup,
    demai_architecture_styles,
    mailbox_preview_markup,
    mission_brief_markup,
    mission_brief_styles,
    render_demai_architecture,
)
from .shared import (
    StageBlockRenderer,
    StageTopCardContent,
    render_mac_window,
    render_stage_top_grid,
)
from .train import (
    TrainingNotesColumn,
    build_inline_note,
    build_launchpad_card,
    build_launchpad_status_item,
    build_token_chip,
    build_train_intro_card,
    build_training_animation_column,
    build_training_notes_column,
    build_nerd_intro_card,
    render_language_mix_chip_rows,
    render_training_animation,
    training_stage_stylesheet,
)
from .use import render_batch_results_panel, render_incoming_preview

__all__ = [
    "ArchitectureCard",
    "TrainingNotesColumn",
    "StageBlockRenderer",
    "StageTopCardContent",
    "build_inline_note",
    "build_launchpad_card",
    "build_launchpad_status_item",
    "build_token_chip",
    "build_train_intro_card",
    "build_training_animation_column",
    "build_training_notes_column",
    "build_nerd_intro_card",
    "data_review_styles",
    "dataset_balance_bar_html",
    "dataset_snapshot_active_badge",
    "dataset_snapshot_card_html",
    "dataset_snapshot_styles",
    "demai_architecture_markup",
    "demai_architecture_styles",
    "edge_case_pairs_html",
    "intro_hero_scoped_css",
    "intro_lifecycle_columns",
    "mailbox_preview_markup",
    "mission_brief_markup",
    "mission_brief_styles",
    "pii_chip_row_html",
    "render_demai_architecture",
    "render_guardrail_audit",
    "render_guardrail_panel",
    "render_threshold_controls",
    "render_intro_hero",
    "render_language_mix_chip_rows",
    "render_mac_window",
    "render_batch_results_panel",
    "render_incoming_preview",
    "render_pii_cleanup_banner",
    "render_pii_indicators",
    "render_stage_top_grid",
    "render_training_animation",
    "stratified_sample_cards_html",
    "terminal",
    "training_stage_stylesheet",
    "_highlight_spans_html",
]
